# Generated by Django 5.2.5 on 2025-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
